// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "controllerDrive.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

controllerDrive::controllerDrive(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveController.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void controllerDrive::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void controllerDrive::Execute() {
	Robot::driveController->driveByController((Robot::oi->getControllerLeftY()), -(Robot::oi->getControllerLeftX()));
	std::cout << "Sending Stick Y's to driveController" << std::endl;
	std::cout << "X = " << Robot::oi->getControllerLeftX() << ", Y = " << Robot::oi->getControllerLeftY() << std::endl;
}

// Make this return true when this Command no longer needs to run execute()
bool controllerDrive::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void controllerDrive::End() {
	Robot::driveController->driveByController(0,0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void controllerDrive::Interrupted() {
	End();
}
