// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "spinLauncherToRpm.h"
#include "WPILib.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

spinLauncherToRpm::spinLauncherToRpm(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::launchController.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void spinLauncherToRpm::Initialize() {
	/*Robot::launchController->wheelsL->SetFeedbackDevice(Robot::launchController->wheelsL->m_feedbackDevice);
	Robot::launchController->wheelsL->ConfigEncoderCodesPerRev(20);

	Robot::launchController->wheelsL->ConfigNominalOutputVoltage(+0.0f, -0.0f);
	Robot::launchController->wheelsL->ConfigPeakOutputVoltage(+12.0f, 0.0f);
	Robot::launchController->wheelsL->SelectProfileSlot(0);
	Robot::launchController->wheelsL->SetP(0);		//These are placeholder values.
	Robot::launchController->wheelsL->SetI(0);			//TODO: Change Values
	Robot::launchController->wheelsL->SetD(0);
	Robot::launchController->wheelsL->SetF(0);*/

}

// Called repeatedly when this Command is scheduled to run
void spinLauncherToRpm::Execute() {
	//
}

// Make this return true when this Command no longer needs to run execute()
bool spinLauncherToRpm::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void spinLauncherToRpm::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void spinLauncherToRpm::Interrupted() {

}
