// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "winMotorsDown.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

winMotorsDown::winMotorsDown(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::elevatorController.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void winMotorsDown::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void winMotorsDown::Execute() {
	//Robot::elevatorController->SetSetpoint();
	//Robot::elevatorController->windowL->
	//Robot::pixyController
	Robot::elevatorController->WindowMotorsDown();
	std::cout << "winMotorsDown : Potentiometer = " << RobotMap::elevatorControllerWindowL->GetAnalogInRaw() << std::endl;
}

// Make this return true when this Command no longer needs to run execute()
bool winMotorsDown::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void winMotorsDown::End() {
	Robot::elevatorController->StopWindowMotors();
	//TODO mke method to get this

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void winMotorsDown::Interrupted() {
	End();
}
